const content = document.getElementById('content');
const toggle = document.getElementById('langToggle');
const subtitle = document.getElementById('subtitle');
let lang = 'pt';

toggle.addEventListener('click', () => {
  if (lang === 'pt') {
      lang = 'en';
          subtitle.textContent = 'Terms of Service & Privacy Policy';
              toggle.textContent = 'Mudar para Português 🇧🇷';
                  content.innerHTML = `
                        <section>
                                <h2>🇺🇸 Terms of Service</h2>
                                        <p>
                                                  By using <strong>Melzona</strong>, you agree to these terms.  
                                                            The bot is designed to help manage Discord servers and provide fun and useful features.
                                                                    </p>
                                                                            <ul>
                                                                                      <li>You must follow the <a href="https://discord.com/terms" target="_blank">Discord Terms of Service</a>.</li>
                                                                                                <li>Abusive use of the bot may result in bans or blocks.</li>
                                                                                                          <li>Features may be changed or removed at any time.</li>
                                                                                                                  </ul>

                                                                                                                          <h2>🇺🇸 Privacy Policy</h2>
                                                                                                                                  <p>
                                                                                                                                            <strong>Melzona</strong> collects basic information such as:
                                                                                                                                                    </p>
                                                                                                                                                            <ul>
                                                                                                                                                                      <li>User and server IDs;</li>
                                                                                                                                                                                <li>Server settings (prefix, permissions, etc.).</li>
                                                                                                                                                                                        </ul>
                                                                                                                                                                                                <p>
                                                                                                                                                                                                          This information is only used to ensure proper bot functionality and is never shared with third parties.  
                                                                                                                                                                                                                    To request data removal, please contact the Melzona team.
                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                  </section>`;
                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                        lang = 'pt';
                                                                                                                                                                                                                                            subtitle.textContent = 'Termos de Serviço & Política de Privacidade';
                                                                                                                                                                                                                                                toggle.textContent = 'Switch to English 🇺🇸';
                                                                                                                                                                                                                                                    content.innerHTML = `
                                                                                                                                                                                                                                                          <section>
                                                                                                                                                                                                                                                                  <h2>🇧🇷 Termos de Serviço</h2>
                                                                                                                                                                                                                                                                          <p>
                                                                                                                                                                                                                                                                                    Ao utilizar o bot <strong>Melzona</strong>, você concorda com estes termos.  
                                                                                                                                                                                                                                                                                              O bot foi criado para ajudar na administração de servidores Discord e oferecer funções divertidas e úteis.
                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                              <ul>
                                                                                                                                                                                                                                                                                                                        <li>Você deve seguir as <a href="https://discord.com/terms" target="_blank">Diretrizes e Termos do Discord</a>.</li>
                                                                                                                                                                                                                                                                                                                                  <li>O uso abusivo do bot pode resultar em banimento ou bloqueio.</li>
                                                                                                                                                                                                                                                                                                                                            <li>As funções do bot podem ser alteradas ou removidas a qualquer momento.</li>
                                                                                                                                                                                                                                                                                                                                                    </ul>

                                                                                                                                                                                                                                                                                                                                                            <h2>🇧🇷 Política de Privacidade</h2>
                                                                                                                                                                                                                                                                                                                                                                    <p>
                                                                                                                                                                                                                                                                                                                                                                              O bot <strong>Melzona</strong> coleta informações básicas como:
                                                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                                                              <ul>
                                                                                                                                                                                                                                                                                                                                                                                                        <li>ID do usuário e do servidor;</li>
                                                                                                                                                                                                                                                                                                                                                                                                                  <li>Configurações de servidor (prefixo, permissões, etc.).</li>
                                                                                                                                                                                                                                                                                                                                                                                                                          </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                  <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                            Essas informações são usadas apenas para o funcionamento do bot e nunca são compartilhadas com terceiros.  
                                                                                                                                                                                                                                                                                                                                                                                                                                                      Para solicitar exclusão de dados, entre em contato com a equipe da Melzona.
                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </section>`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });